import Head from "next/head";
import { useState, useEffect } from "react";
import { Banner, Products, Category, Gallery, Layout } from "../components";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Frontend Mentor | Audiophile e-commerce website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Banner />
        <Products />
        <Category />
        <Gallery />
      </Layout>
    </div>
  );
}
