import Head from "next/head";
import { useState, useEffect } from "react";
import {
  Header,
  Banner,
  Products,
  Speaker,
  SpeakerProduct,
  Earphone,
  Gallery,
  Footer,
  Layout,
} from "../components";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Frontend Mentor | Audiophile e-commerce website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Banner />
        <Products />
        <Speaker />
        <SpeakerProduct />
        <Earphone />
        <Gallery />
      </Layout>
    </div>
  );
}
