import Head from "next/head";
import Image from "next/image";
import { Header, Banner } from "../components";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Frontend Mentor | Audiophile e-commerce website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="">
        <Banner />
      </main>
    </div>
  );
}
